<?php
// Auto-generated by Pengaturan. Jangan edit manual.
return [
    'app_name'         => 'Wisnu Wibisono',
    'site_title'       => 'Portofolio Wisnu Wibisono',
    'site_description' => 'Web Developer & UI Designer',
    'maintenance'      => true,
];
